Tiny safeguard for when there's a failure getting ffmpeg

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -18,6 +18,11 @@ mkdir -p ffmpeg
 cd ffmpeg
 curl -L --silent $DOWNLOAD_URL | tar xJ --strip-components=1
 
+if [ ! -f "./ffmpeg" ]; then
+    echo "Failed to properly download/extract ffmpeg. Aborting" | indent
+    exit 1
+fi
+
 echo "exporting PATH" | indent
 PROFILE_PATH="$BUILD_DIR/.profile.d/ffmpeg.sh"
 mkdir -p $(dirname $PROFILE_PATH)
